### ISSUE TITLE
entry keyword

### ISSUE THREAD

**Issue by iddq** [caisah/K-and-R-exercises-and-examples#2]
Was the entry keyword part of K&R standard? I miss it from the examples.

**Comment by caisah** [comment]
Sorry, I don't understand what you're referring to...

**Comment by iddq** [comment]
Sorry, so far as I know the first edition of K&R book contains the explanation of "entry" keyword. That was part of the early implementation of K&R standard. It was removed later so you cannot find it in the 2nd version of book. I thought you've created examples or use examples from the 1st edition of book...
